config/routes.rb
Rails.application.routes.draw do

  concern :supports_reordering do
    post :reorder, on: :collection
  end

  # Enable /sidekiq for admin users only
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  get '404' => redirect('404-page')
  get '500' => redirect('500-page')

  namespace :api do
    post 'stripe_v01', to: 'stripe_v01#create'
    post 'stripe_v02', to: 'stripe_v02#create'
  end

  # all standard, user-facing "resources" go inside this scope
  scope '(:locale)', locale: /en/ do # /en\nl\pl/
    get '404' => redirect('404-page')
    get '500' => redirect('500-page')

    # users and authentication
    resources :users do
      resources :visits, only: [:index, :show]
    end

    get 'new_subscription', to: 'subscriptions#new', as: :new_subscription
    get 'users/:user_id/new_subscription', to: 'subscriptions#new'
    post 'create_subscription/:user_id', to: 'subscriptions#create', as: :create_subscription

    #User Account Verification
    get 'user_verification/:email_verification_code', to: 'user_verifications#update',
        as: :user_verification
    get 'account_verified', to: 'user_verifications#account_verified',
        as: :account_verified
    post 'resend_verification_mail/:email_verification_code', to: 'user_verifications#resend_verification_mail', as: :resend_verification_mail

    # User Sessions
    get 'sign_in', to: 'user_sessions#new', as: :sign_in
    resources :user_sessions, only: [:create]
    get 'sign_out', to: 'user_sessions#destroy', as: :sign_out

    # User Accounts
    get 'account', to: 'user_accounts#account_show', as: :account
    post 'change_password', to: 'user_accounts#change_password', as: :change_password
    patch 'update_user_details', to: 'user_accounts#update_user', as: :update_personal_details
    get 'subscription_invoice/:id', to: 'user_accounts#subscription_invoice', as: :subscription_invoices
    get 'account/change_plan', to: 'subscriptions#change_plan', as: :account_change_plan
    put 'un_cancel_subscription/:id', to: 'subscriptions#un_cancel_subscription', as: :un_cancel_subscription

    resources :user_groups
    resources :student_user_management
    resources :subscription_management do
      get '/invoice/:invoice_id', action: :invoice, as: :invoice
      get '/pdf_invoice/:invoice_id', action: :pdf_invoice, as: :pdf_invoice
      get '/invoice/:invoice_id/charge/:id', action: :charge, as: :invoice_charge
      put '/cancel', action: :cancel, as: :cancel
      put '/un_cancel', action: :un_cancel_subscription, as: :un_cancel_subscription
      put '/immediate_cancel', action: :immediate_cancel, as: :immediate_cancel
    end
    get  'student_user_management/:id/convert_to_student', to: 'student_user_management#convert_to_student', as: :convert_to_student
    patch  'student_user_management/:id/update_to_student', to: 'student_user_management#update_to_student', as: :update_to_student
    resources :users do
      get  '/personal', action: :user_personal_details, as: :personal
      get  '/subscription', action: :user_subscription_status, as: :subscription
      get  '/courses', action: :user_courses_status, as: :courses
      get  '/enrollments', action: :user_enrollments_details, as: :enrollments
      get  '/orders', action: :user_purchases_details, as: :orders
      patch  '/update_courses', action: :update_courses, as: :update_courses
    end
    resources :user_passwords, only: [:new, :edit, :create, :update]
    get 'forgot_password', to: 'user_passwords#new', as: :forgot_password
    get 'reset_password/:id', to: 'user_passwords#edit', as: :reset_password
    get 'set_password/:id', to: 'user_passwords#set_password', as: :set_password
    put 'create_password/:id', to: 'user_passwords#create_password', as: :user_create_password
    post 'manager_resend/:id', to: 'user_passwords#manager_resend_email', as: :manager_resend

    # Internal Landing Pages - post sign-up or upgrade or purchase
    get 'personal_sign_up_complete/:account_activation_code', to: 'student_sign_ups#show', as: :personal_sign_up_complete
    get 'personal_upgrade_complete', to: 'subscriptions#personal_upgrade_complete', as: :personal_upgrade_complete

    get 'courses/:subject_course_name_url/:course_module_name_url(/:course_module_element_name_url)', to: 'courses#show', as: :course
    get 'courses/:subject_course_name_url',
        to: redirect('/%{locale}/library/%{subject_course_name_url}')

    resources :countries, concerns: :supports_reordering
    resources :coupons
    post '/coupon_validation', to: 'coupons#validate_coupon', as: :coupon_validation
    resources :courses, only: [:create] do
      match :create_video_user_log, on: :collection, via: [:post]
      match :video_watched_data, on: :collection, via: [:put, :patch]
    end
    get '/enrollments/basic_create/:subject_course_name_url', to: 'enrollments#basic_create', as: :enrollment_basic_create
    get '/enrollments/admin_show/:id', to: 'enrollments#admin_show', as: :enrollment_admin_show
    get '/enrollments/admin_edit/:id', to: 'enrollments#admin_edit', as: :enrollment_admin_edit
    patch '/enrollments/admin_update/:id', to: 'enrollments#admin_update', as: :enrollment_admin_update
    get '/enrollments/reset_progress/:id', to: 'enrollments#admin_create_new_scul', as: :admin_create_new_scul
    resources :enrollments, only: [:edit, :update, :create]
    get 'course_modules/:subject_course_name_url',
        to: 'course_modules#new',
        as: :new_course_modules_for_subject_course_and_name
    get 'course_modules/:subject_course_name_url', to: 'course_modules#show',
        as: :course_modules_for_subject_course
    resources :course_modules, concerns: :supports_reordering
    resources :course_module_elements, except: [:index], concerns: :supports_reordering
    get 'course_module_elements/:id/quiz_questions_order', to: 'course_module_elements#quiz_questions_order', as: :quiz_questions_order
    resources :currencies, concerns: :supports_reordering

    get '/dashboard', to: 'dashboard#show', as: :student_dashboard

    resources :exam_bodies
    resources :exam_sittings
    resources :groups, concerns: :supports_reordering

    #Sign Up Actions
    get '/student_new', to: 'student_sign_ups#new', as: :new_student
    post '/student_create', to: 'student_sign_ups#create', as: :create_student

    resources :invoices, only: [:index, :show]

    post '/subscribe', to: 'library#subscribe'
    post '/home_page_subscribe', to: 'student_sign_ups#subscribe'
    post '/info_subscribe', to: 'footer_pages#info_subscribe'
    post '/complaints_intercom', to: 'footer_pages#complaints_intercom'
    post '/contact_us_intercom', to: 'footer_pages#contact_us_intercom'
    post '/tutor_contact_form', to: 'library#tutor_contact_form'

    # Library Structure

    get 'library', to: 'library#index', as: :library
    get 'library/:group_name_url', to: 'library#group_show', as: :library_group
    get 'library/:group_name_url/:subject_course_name_url', to: 'library#course_show', as: :library_course

    resources :management_consoles
    get '/system_requirements', to: 'management_consoles#system_requirements', as: :system_requirements
    resources :mock_exams, concerns: :supports_reordering
    resources :orders, except: [:new]
    get 'order/new/:product_id', to: 'orders#new', as: :new_order
    get 'order/order_complete/:reference_guid', to: 'orders#order_complete', as: :order_complete
    resources :products
    resources :quiz_questions, except: [:index], concerns: :supports_reordering

    get '/reports', to: 'reports#index', as: :reports
    get '/export_users', to: 'reports#export_users', as: :export_users
    get '/export_users_monthly', to: 'reports#export_users_monthly', as: :export_users_monthly
    get '/export_users_with_enrollments', to: 'reports#export_users_with_enrollments', as: :export_users_with_enrollments
    get '/export_visits', to: 'reports#export_visits', as: :export_visits
    get '/export_courses', to: 'reports#export_courses', as: :export_courses
    get '/export_enrollments', to: 'reports#export_enrollments', as: :export_enrollments


    resources :subject_courses, concerns: :supports_reordering do
      get 'edit_tutors', action: :edit_tutors, as: :edit_course_tutors
      patch 'update_tutors', action: :update_tutors, as: :update_course_tutors
    end
    get 'subject_courses/:id/course_modules_order', to: 'subject_courses#course_modules_order', as: :course_modules_order
    post 'subject_courses/:id/update_user_logs', to: 'subject_courses#update_student_exam_tracks', as: :subject_course_update_user_logs
    get 'subject_courses/:id/resources', to: 'subject_courses#subject_course_resources', as: :course_resources
    get 'subject_courses/:id/new_subject_course_resources', to: 'subject_courses#new_subject_course_resources', as: :new_course_resources
    post 'subject_courses/:id/create_subject_course_resources', to: 'subject_courses#create_subject_course_resources', as: :create_course_resources

    resources :subscriptions, only: [:update, :destroy]
    resources :subscription_payment_cards, only: [:create, :update, :destroy]
    resources :subscription_plans
    resources :subscription_plan_categories
    get '/all_subscriptions', to: 'subscription_plans#all_subscriptions', as: :all_subscriptions
    get '/subscription_show/:id', to: 'subscription_plans#subscription_show', as: :subscription_show

    resources :subject_course_resources
    get 'pricing', to: 'subscription_plans#public_index', as: :pricing
    get 'acca_info', to: 'footer_pages#acca_info'
    get 'contact', to: 'footer_pages#contact'
    get 'privacy_policy', to: 'footer_pages#privacy_policy'
    get 'terms_and_conditions', to: 'footer_pages#terms_and_conditions'
    get 'profile/:id', to: 'footer_pages#profile', as: :profile
    get 'profiles', to: 'footer_pages#profile_index', as: :tutors

    resources :user_notifications

app/models/subject_course_resource.rb
# == Schema Information
#
# Table name: subject_course_resources
#
#  id                       :integer          not null, primary key
#  name                     :string
#  subject_course_id        :integer
#  description              :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  file_upload_file_name    :string
#  file_upload_content_type :string
#  file_upload_file_size    :integer
#  file_upload_updated_at   :datetime
#

class SubjectCourseResource < ActiveRecord::Base

  # attr-accessible
  attr_accessible :name, :subject_course_id, :description, :file_upload

  # Constants

  # relationships
  belongs_to :subject_course
  has_attached_file :file_upload, default_url: '/assets/images/missing_corporate_logo.png'

  # validation
  validates :name, presence: true
  validates :subject_course_id, presence: true,
            numericality: {only_integer: true, greater_than: 0}
  validates_attachment_content_type :file_upload,
                                    content_type: %w(image/jpg image/jpeg image/png image/gif application/pdf application/xlsx application/xls application/doc application/docx application/vnd.openxmlformats-officedocument.wordprocessingml.document text/csv application/octet-stream application/vnd.openxmlformats-officedocument.spreadsheetml.sheet application/vnd.ms-excel.sheet.macroenabled.12 application/vnd.openxmlformats-officedocument.presentationml.presentation text/css)

  # callbacks
  before_destroy :check_dependencies

  # scopes
  scope :all_in_order, -> { order(:name) }

  # class methods

  # instance methods
  def destroyable?
    true
  end

  protected

  def check_dependencies
    unless self.destroyable?
      errors.add(:base, I18n.t('models.general.dependencies_exist'))
      false
    end
  end

end

app/controllers/subject_course_resources_controller.rb
# == Schema Information
#
# Table name: subject_course_resources
#
#  id                       :integer          not null, primary key
#  name                     :string
#  subject_course_id        :integer
#  description              :text
#  created_at               :datetime         not null
#  updated_at               :datetime         not null
#  file_upload_file_name    :string
#  file_upload_content_type :string
#  file_upload_file_size    :integer
#  file_upload_updated_at   :datetime
#

class SubjectCourseResourcesController < ApplicationController

  before_action :logged_in_required
  before_action do
    ensure_user_has_access_rights(%w(content_management_access))
  end
  before_action :get_variables

  def index
    @subject_course_resources = SubjectCourseResource.paginate(per_page: 50, page: params[:page]).all_in_order
  end

  def show
  end

  def new
    @subject_course_resource = SubjectCourseResource.new
  end

  def edit
  end

  def create
    @subject_course_resource = SubjectCourseResource.new(allowed_params)
    if @subject_course_resource.save
      flash[:success] = I18n.t('controllers.subject_course_resources.create.flash.success')
      redirect_to course_resources_url(@subject_course_resource.subject_course)
    else
      render action: :new
    end
  end

  def update
    if @subject_course_resource.update_attributes(allowed_params)
      flash[:success] = I18n.t('controllers.subject_course_resources.update.flash.success')
      redirect_to course_resources_url(@subject_course_resource.subject_course)
    else
      render action: :edit
    end
  end

  def destroy
    if @subject_course_resource.destroy
      flash[:success] = I18n.t('controllers.subject_course_resources.destroy.flash.success')
    else
      flash[:error] = I18n.t('controllers.subject_course_resources.destroy.flash.error')
    end
    redirect_to subject_course_resources_url
  end

  protected

  def get_variables
    if params[:id].to_i > 0
      @subject_course_resource = SubjectCourseResource.where(id: params[:id]).first
    end
    @subject_courses = SubjectCourse.all_active.all_in_order
  end

  def allowed_params
    params.require(:subject_course_resource).permit(:name, :subject_course_id, :description, :file_upload)
  end

end

app/views/subject_course_resources/_form.html.haml
=form_for(@subject_course_resource, url: (controller_name == 'subject_course_resources' ? subject_course_resource_url : create_course_resources_url), html: {class: 'form-horizontal', role: 'form'}) do |f|
  .row
    .col-md-8.col-md-offset-2
      =render partial: '/layouts/error_messages', locals: {thing: @subject_course_resource, message: nil}
      =f.label :name, t('views.subject_course_resources.form.name'), class: 'control-label'
      .input-group.input-group-lg.full-width
        =f.text_field :name, placeholder: t('views.subject_course_resources.form.name_placeholder'), class: 'form-control', style: 'border-radius: 6px;', autofocus: true
      %br/
      -if controller_name == 'subject_course_resources'
        =f.label :subject_course_id, t('views.subject_course_resources.form.subject_course_id'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.collection_select :subject_course_id, @subject_courses, :id, :name, {include_blank: t('views.general.select')}, {class: 'form-control', style: 'border-radius: 6px;'}
        %br/
      =f.label :description, t('views.subject_course_resources.form.description'), class: 'control-label'
      .input-group.input-group-lg.full-width
        =f.text_area :description, placeholder: t('views.subject_course_resources.form.description_placeholder'), rows: 4, class: 'form-control', style: 'border-radius: 6px;'

      %br/
      =f.label :file_upload, t('views.course_module_element_resources.form.upload'), class: 'control-label'
      -if f.object.file_upload_file_name
        .form-control-static
          =link_to f.object.file_upload_file_name, f.object.file_upload.url, target: '_blank'
          =number_to_human_size(f.object.file_upload_file_size)
          %br/
          %br/

        .input-group.input-group-lg.form-control
          =f.label :file_upload, t('views.course_module_element_resources.form.replace')
          =f.file_field :file_upload, style: 'border-radius: 6px;'
          %p{style: 'margin: 10px 0;'}
      -else
        .input-group.input-group-lg
          =f.file_field :file_upload, class: 'form-control', style: 'border-radius: 6px;'



      .row
        .col-md-12.l-margin-top-huge
          =f.submit t('views.general.save'), class: 'btn btn-red'
          =t('views.general.or')
          -if controller_name == 'subject_course_resources'
            =link_to t('views.general.cancel'), subject_course_resources_path, class: 'btn btn-cyan'
          -else
            =link_to t('views.general.cancel'), course_resources_url(@subject_course_resource.subject_course), class: 'btn btn-purple'

app/views/subject_course_resources/edit.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.subject_course_resources.edit.h1')
      =render partial: 'form'

app/views/subject_course_resources/index.html.haml
.l-section-small.is-bg-asphalt{style: 'padding-left: 30px; padding-right: 30px;'}
  .container-fluid.l-padding-side-3x
    .row.l-margin-bottom.l-margin-top
      .col-md-12.col-sm-12.col-xs-12.text-center
        %h1.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
          =t('views.subject_course_resources.index.h1')

      .col-md-12.l-margin-top-big
        .corporate-box-item.table-box
          .table-responsive
            %table.table.sorted_table{style: 'font-size: 18px;'}
              %thead
                %tr
                  %th=t('views.subject_course_resources.form.name')
                  %th=t('views.subject_course_resources.form.subject_course_id')
                  %th
              %tbody
                -@subject_course_resources.each do |subject_course_resource|
                  %tr
                    %td=subject_course_resource.name
                    -if subject_course_resource.subject_course
                      %td=subject_course_resource.subject_course.name
                    %td
                      =link_to t('views.general.view'), subject_course_resource.file_upload.url, target: '_blank', class: 'btn btn-purple btn-small'
                      =link_to t('views.general.edit'), edit_subject_course_resource_url(subject_course_resource), class: 'btn btn-cyan btn-small'
                      -if subject_course_resource.destroyable?
                        =link_to t('views.general.delete'), subject_course_resource, method: :delete, data: { confirm: t('views.general.delete_confirmation') }, class: 'btn btn-red btn-small'

    .row
      =link_to t('views.general.new'), new_subject_course_resource_url, class: 'btn btn-red', title: t('views.general.new_tooltip')

app/views/subject_course_resources/new.html.haml
.l-section-small.is-bg-asphalt.margin-top
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.subject_course_resources.new.h1')
    =render partial: 'form'

app/views/subject_course_resources/show.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.subject_course_resources.show.h1')
            \#
            =@subject_course_resource.id
      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          .table-box
            .table-responsive
              %table.table.table-bordered.l-margin-top
                %tr
                  %td.col-sm-4=t('views.subject_course_resources.form.name')
                  %td.col-sm-8=@subject_course_resource.name
                %tr
                  %td.col-sm-4=t('views.subject_course_resources.form.subject_course_id')
                  %td.col-sm-8=@subject_course_resource.subject_course.name
                %tr
                  %td.col-sm-4=t('views.subject_course_resources.form.description')
                  %td.col-sm-8=@subject_course_resource.description
              %p
                =link_to t('views.general.back'), subject_course_resources_url
                |
                =link_to t('views.general.edit'), edit_subject_course_resource_url(id: @subject_course_resource.id), title: t('views.general.edit_tooltip')