config/routes.rb
Rails.application.routes.draw do

  concern :supports_reordering do
    post :reorder, on: :collection
  end

  # Enable /sidekiq for admin users only
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  get '404' => redirect('404-page')
  get '500' => redirect('500-page')

  namespace :api do
    post 'stripe_v01', to: 'stripe_v01#create'
    post 'stripe_v02', to: 'stripe_v02#create'
  end

  # all standard, user-facing "resources" go inside this scope
  scope '(:locale)', locale: /en/ do # /en\nl\pl/
    get '404' => redirect('404-page')
    get '500' => redirect('500-page')

    # users and authentication
    resources :users do
      resources :visits, only: [:index, :show]
    end

    get 'new_subscription', to: 'subscriptions#new', as: :new_subscription
    get 'users/:user_id/new_subscription', to: 'subscriptions#new'
    post 'create_subscription/:user_id', to: 'subscriptions#create', as: :create_subscription

    #User Account Verification
    get 'user_verification/:email_verification_code', to: 'user_verifications#update',
        as: :user_verification
    get 'account_verified', to: 'user_verifications#account_verified',
        as: :account_verified
    post 'resend_verification_mail/:email_verification_code', to: 'user_verifications#resend_verification_mail', as: :resend_verification_mail

    # User Sessions
    get 'sign_in', to: 'user_sessions#new', as: :sign_in
    resources :user_sessions, only: [:create]
    get 'sign_out', to: 'user_sessions#destroy', as: :sign_out

    # User Accounts
    get 'account', to: 'user_accounts#account_show', as: :account
    post 'change_password', to: 'user_accounts#change_password', as: :change_password
    patch 'update_user_details', to: 'user_accounts#update_user', as: :update_personal_details
    get 'subscription_invoice/:id', to: 'user_accounts#subscription_invoice', as: :subscription_invoices
    get 'account/change_plan', to: 'subscriptions#change_plan', as: :account_change_plan
    put 'un_cancel_subscription/:id', to: 'subscriptions#un_cancel_subscription', as: :un_cancel_subscription

    resources :user_groups
    resources :student_user_management
    resources :subscription_management do
      get '/invoice/:invoice_id', action: :invoice, as: :invoice
      get '/pdf_invoice/:invoice_id', action: :pdf_invoice, as: :pdf_invoice
      get '/invoice/:invoice_id/charge/:id', action: :charge, as: :invoice_charge
      put '/cancel', action: :cancel, as: :cancel
      put '/un_cancel', action: :un_cancel_subscription, as: :un_cancel_subscription
      put '/immediate_cancel', action: :immediate_cancel, as: :immediate_cancel
    end
    get  'student_user_management/:id/convert_to_student', to: 'student_user_management#convert_to_student', as: :convert_to_student
    patch  'student_user_management/:id/update_to_student', to: 'student_user_management#update_to_student', as: :update_to_student
    resources :users do
      get  '/personal', action: :user_personal_details, as: :personal
      get  '/subscription', action: :user_subscription_status, as: :subscription
      get  '/courses', action: :user_courses_status, as: :courses
      get  '/enrollments', action: :user_enrollments_details, as: :enrollments
      get  '/orders', action: :user_purchases_details, as: :orders
      patch  '/update_courses', action: :update_courses, as: :update_courses
    end
    resources :user_passwords, only: [:new, :edit, :create, :update]
    get 'forgot_password', to: 'user_passwords#new', as: :forgot_password
    get 'reset_password/:id', to: 'user_passwords#edit', as: :reset_password
    get 'set_password/:id', to: 'user_passwords#set_password', as: :set_password
    put 'create_password/:id', to: 'user_passwords#create_password', as: :user_create_password
    post 'manager_resend/:id', to: 'user_passwords#manager_resend_email', as: :manager_resend

    # Internal Landing Pages - post sign-up or upgrade or purchase
    get 'personal_sign_up_complete/:account_activation_code', to: 'student_sign_ups#show', as: :personal_sign_up_complete
    get 'personal_upgrade_complete', to: 'subscriptions#personal_upgrade_complete', as: :personal_upgrade_complete

    get 'courses/:subject_course_name_url/:course_module_name_url(/:course_module_element_name_url)', to: 'courses#show', as: :course
    get 'courses/:subject_course_name_url',
        to: redirect('/%{locale}/library/%{subject_course_name_url}')

    resources :countries, concerns: :supports_reordering
    resources :coupons
    post '/coupon_validation', to: 'coupons#validate_coupon', as: :coupon_validation
    resources :courses, only: [:create] do
      match :create_video_user_log, on: :collection, via: [:post]
      match :video_watched_data, on: :collection, via: [:put, :patch]
    end
    get '/enrollments/basic_create/:subject_course_name_url', to: 'enrollments#basic_create', as: :enrollment_basic_create
    get '/enrollments/admin_show/:id', to: 'enrollments#admin_show', as: :enrollment_admin_show
    get '/enrollments/admin_edit/:id', to: 'enrollments#admin_edit', as: :enrollment_admin_edit
    patch '/enrollments/admin_update/:id', to: 'enrollments#admin_update', as: :enrollment_admin_update
    get '/enrollments/reset_progress/:id', to: 'enrollments#admin_create_new_scul', as: :admin_create_new_scul
    resources :enrollments, only: [:edit, :update, :create]
    get 'course_modules/:subject_course_name_url',
        to: 'course_modules#new',
        as: :new_course_modules_for_subject_course_and_name
    get 'course_modules/:subject_course_name_url', to: 'course_modules#show',
        as: :course_modules_for_subject_course
    resources :course_modules, concerns: :supports_reordering
    resources :course_module_elements, except: [:index], concerns: :supports_reordering
    get 'course_module_elements/:id/quiz_questions_order', to: 'course_module_elements#quiz_questions_order', as: :quiz_questions_order
    resources :currencies, concerns: :supports_reordering

    get '/dashboard', to: 'dashboard#show', as: :student_dashboard

    resources :exam_bodies
    resources :exam_sittings
    resources :groups, concerns: :supports_reordering

    #Sign Up Actions
    get '/student_new', to: 'student_sign_ups#new', as: :new_student
    post '/student_create', to: 'student_sign_ups#create', as: :create_student

    resources :invoices, only: [:index, :show]

    post '/subscribe', to: 'library#subscribe'
    post '/home_page_subscribe', to: 'student_sign_ups#subscribe'
    post '/info_subscribe', to: 'footer_pages#info_subscribe'
    post '/complaints_intercom', to: 'footer_pages#complaints_intercom'
    post '/contact_us_intercom', to: 'footer_pages#contact_us_intercom'
    post '/tutor_contact_form', to: 'library#tutor_contact_form'

    # Library Structure

    get 'library', to: 'library#index', as: :library
    get 'library/:group_name_url', to: 'library#group_show', as: :library_group
    get 'library/:group_name_url/:subject_course_name_url', to: 'library#course_show', as: :library_course

    resources :management_consoles
    get '/system_requirements', to: 'management_consoles#system_requirements', as: :system_requirements
    resources :mock_exams, concerns: :supports_reordering
    resources :orders, except: [:new]
    get 'order/new/:product_id', to: 'orders#new', as: :new_order
    get 'order/order_complete/:reference_guid', to: 'orders#order_complete', as: :order_complete
    resources :products
    resources :quiz_questions, except: [:index], concerns: :supports_reordering

    get '/reports', to: 'reports#index', as: :reports
    get '/export_users', to: 'reports#export_users', as: :export_users
    get '/export_users_monthly', to: 'reports#export_users_monthly', as: :export_users_monthly
    get '/export_users_with_enrollments', to: 'reports#export_users_with_enrollments', as: :export_users_with_enrollments
    get '/export_visits', to: 'reports#export_visits', as: :export_visits
    get '/export_courses', to: 'reports#export_courses', as: :export_courses
    get '/export_enrollments', to: 'reports#export_enrollments', as: :export_enrollments


    resources :subject_courses, concerns: :supports_reordering do
      get 'edit_tutors', action: :edit_tutors, as: :edit_course_tutors
      patch 'update_tutors', action: :update_tutors, as: :update_course_tutors
    end
    get 'subject_courses/:id/course_modules_order', to: 'subject_courses#course_modules_order', as: :course_modules_order
    post 'subject_courses/:id/update_user_logs', to: 'subject_courses#update_student_exam_tracks', as: :subject_course_update_user_logs
    get 'subject_courses/:id/resources', to: 'subject_courses#subject_course_resources', as: :course_resources
    get 'subject_courses/:id/new_subject_course_resources', to: 'subject_courses#new_subject_course_resources', as: :new_course_resources
    post 'subject_courses/:id/create_subject_course_resources', to: 'subject_courses#create_subject_course_resources', as: :create_course_resources

    resources :subscriptions, only: [:update, :destroy]
    resources :subscription_payment_cards, only: [:create, :update, :destroy]
    resources :subscription_plans
    resources :subscription_plan_categories
    get '/all_subscriptions', to: 'subscription_plans#all_subscriptions', as: :all_subscriptions
    get '/subscription_show/:id', to: 'subscription_plans#subscription_show', as: :subscription_show

    resources :subject_course_resources
    get 'pricing', to: 'subscription_plans#public_index', as: :pricing
    get 'acca_info', to: 'footer_pages#acca_info'
    get 'contact', to: 'footer_pages#contact'
    get 'privacy_policy', to: 'footer_pages#privacy_policy'
    get 'terms_and_conditions', to: 'footer_pages#terms_and_conditions'
    get 'profile/:id', to: 'footer_pages#profile', as: :profile
    get 'profiles', to: 'footer_pages#profile_index', as: :tutors

    resources :user_notifications

app/models/user_group.rb
# == Schema Information
#
# Table name: user_groups
#
#  id                           :integer          not null, primary key
#  name                         :string
#  description                  :text
#  individual_student           :boolean          default(FALSE), not null
#  tutor                        :boolean          default(FALSE), not null
#  content_manager              :boolean          default(FALSE), not null
#  blogger                      :boolean          default(FALSE), not null
#  site_admin                   :boolean          default(FALSE), not null
#  created_at                   :datetime
#  updated_at                   :datetime
#  complimentary                :boolean          default(FALSE)
#  customer_support             :boolean          default(FALSE)
#  marketing_support            :boolean          default(FALSE)
#  system_requirements_access   :boolean          default(FALSE)
#  content_management_access    :boolean          default(FALSE)
#  stripe_management_access     :boolean          default(FALSE)
#  user_management_access       :boolean          default(FALSE)
#  developer_access             :boolean          default(FALSE)
#  home_pages_access            :boolean          default(FALSE)
#  user_group_management_access :boolean          default(FALSE)
#  student_user                 :boolean          default(FALSE)
#  trial_or_sub_required        :boolean          default(FALSE)
#  blocked_user                 :boolean          default(FALSE)
#

class UserGroup < ActiveRecord::Base

  include LearnSignalModelExtras

  # attr-accessible
  attr_accessible :name, :description, :system_requirements_access,
                  :content_management_access, :stripe_management_access,
                  :user_management_access, :developer_access,
                  :home_pages_access, :user_group_management_access,
                  :student_user, :trial_or_sub_required, :blocked_user,
                  :tutor
  # Constants

  # relationships
  has_many :users

  # validation
  validates :name, presence: true, uniqueness: true, length: { maximum: 255}
  validates :description, presence: true

  # callbacks
  before_validation { squish_fields(:name, :description) }

  # scopes
  scope :all_in_order, -> { order(:name) }
  scope :all_not_student, -> { where(student_user: false) }
  scope :all_student, -> { where(student_user: true) }
  scope :all_trial_or_sub, -> { where(trial_or_sub_required: true) }

  # class methods

  # instance methods
  def destroyable?
    self.users.empty?
  end

  def set_new_attributes
    if self.site_admin
      self.system_requirements_access = true
      self.content_management_access = true
      self.stripe_management_access = true
      self.user_management_access = true
      self.developer_access = true
      self.user_group_management_access = true

    elsif self.content_manager
      self.content_management_access = true

    elsif self.complimentary
      self.student_user = true
      self.trial_or_sub_required = false
      self.blocked_user = false

    elsif self.customer_support
      self.content_management_access = true
      self.user_management_access = true

    elsif self.marketing_support
      self.home_pages_access = true

    elsif self.individual_student
      self.student_user = true
      self.trial_or_sub_required = true

    elsif self.name == 'Blocked User'
      self.student_user = true
      self.trial_or_sub_required = true
      self.blocked_user = true
    end

    self.save
  end

  protected

end

app/controllers/user_groups_controller.rb
# == Schema Information
#
# Table name: user_groups
#
#  id                           :integer          not null, primary key
#  name                         :string
#  description                  :text
#  individual_student           :boolean          default(FALSE), not null
#  tutor                        :boolean          default(FALSE), not null
#  content_manager              :boolean          default(FALSE), not null
#  blogger                      :boolean          default(FALSE), not null
#  site_admin                   :boolean          default(FALSE), not null
#  created_at                   :datetime
#  updated_at                   :datetime
#  complimentary                :boolean          default(FALSE)
#  customer_support             :boolean          default(FALSE)
#  marketing_support            :boolean          default(FALSE)
#  system_requirements_access   :boolean          default(FALSE)
#  content_management_access    :boolean          default(FALSE)
#  stripe_management_access     :boolean          default(FALSE)
#  user_management_access       :boolean          default(FALSE)
#  developer_access             :boolean          default(FALSE)
#  home_pages_access            :boolean          default(FALSE)
#  user_group_management_access :boolean          default(FALSE)
#  student_user                 :boolean          default(FALSE)
#  trial_or_sub_required        :boolean          default(FALSE)
#  blocked_user                 :boolean          default(FALSE)
#

class UserGroupsController < ApplicationController

  before_action :logged_in_required
  before_action do
    ensure_user_has_access_rights(%w(user_group_management_access))
  end
  before_action :get_variables

  def index
    @user_groups = UserGroup.paginate(per_page: 50, page: params[:page]).all_in_order
  end

  def show
  end

  def new
    @user_group = UserGroup.new
  end

  def edit
  end

  def create
    @user_group = UserGroup.new(allowed_params)
    if @user_group.save
      flash[:success] = I18n.t('controllers.user_groups.create.flash.success')
      redirect_to user_groups_url
    else
      render action: :new
    end
  end

  def update
    if @user_group.update_attributes(allowed_params)
      flash[:success] = I18n.t('controllers.user_groups.update.flash.success')
      redirect_to user_groups_url
    else
      render action: :edit
    end
  end

  def destroy
    if @user_group.destroy
      flash[:success] = I18n.t('controllers.user_groups.destroy.flash.success')
    else
      flash[:error] = I18n.t('controllers.user_groups.destroy.flash.error')
    end
    redirect_to user_groups_url
  end

  protected

  def get_variables
    if params[:id].to_i > 0
      @user_group = UserGroup.where(id: params[:id]).first
    end
    seo_title_maker(@user_group.try(:name) || 'User groups', '', true)
    @layout = 'management'
  end

  def allowed_params
    params.require(:user_group).permit(:name, :description, :system_requirements_access,
                                       :content_management_access, :stripe_management_access,
                                       :user_management_access, :developer_access,
                                       :home_pages_access, :user_group_management_access,
                                       :student_user, :trial_or_sub_required, :blocked_user,
                                       :tutor)
  end

end

app/views/user_groups/_form.html.haml
=form_for(@user_group, html: {class: 'form-horizontal', role: 'form'}) do |f|
  .row
    .col-sm-12
      .col-md-6
        =render partial: '/layouts/error_messages', locals: {thing: @user_group, message: nil}
        =f.label :name, t('views.user_groups.form.name'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_field :name, placeholder: t('views.user_groups.form.name_placeholder'), class: 'form-control', style: 'border-radius: 6px;', autofocus: true

      .col-md-6

        =f.label :description, t('views.user_groups.form.description'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_area :description, placeholder: t('views.user_groups.form.description_placeholder'), rows: 4, class: 'form-control', style: 'border-radius: 6px;'


  .row
    .col-sm-12.l-margin-top
      .box-item
        .col-sm-12
          .h6.l-margin-bottom
            Student Access
          .col-sm-6
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :student_user
                    =t('views.user_groups.form.student_user')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :blocked_user
                    =t('views.user_groups.form.blocked_user')


          .col-sm-6
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :trial_or_sub_required
                    =t('views.user_groups.form.trial_or_sub_required')




  .row
    .col-sm-12.l-margin-top
      .box-item
        .col-sm-12
          .col-sm-6
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :system_requirements_access
                    =t('views.user_groups.form.system_requirements_access')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :content_management_access
                    =t('views.user_groups.form.content_management_access')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :stripe_management_access
                    =t('views.user_groups.form.stripe_management_access')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :user_management_access
                    =t('views.user_groups.form.user_management_access')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :developer_access
                    =t('views.user_groups.form.developer_access')

          .col-sm-6
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :home_pages_access
                    =t('views.user_groups.form.home_pages_access')
            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :user_group_management_access
                    =t('views.user_groups.form.user_group_management_access')

            .form-group
              .col-sm-12
                .checkbox
                  %label
                    =f.check_box :tutor
                    =t('views.user_groups.form.tutor')





  .row.l-margin-top-big
    =f.submit t('views.general.save'), class: 'btn btn-red'
    =link_to t('views.general.cancel'), user_groups_path, class: 'btn btn-cyan'

app/views/user_groups/edit.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.user_groups.edit.h1')
      =render partial: 'form'

app/views/user_groups/index.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.user_groups.index.h1')

      .row.l-margin-top.l-margin-bottom
        .col-md-12
          =render partial: 'management_consoles/user_management_nav'


      .row.l-margin-top.l-margin-bottom
        .col-md-4.col-sm-4.l-margin-top
          =link_to 'New User Group', new_user_group_url, class: 'btn btn-red', title: t('views.general.new_tooltip')


        .col-md-12.l-margin-top-big
          .table-box
            .table-responsive
              =will_paginate @user_groups, renderer: BootstrapPagination::Rails
              %table.table
                %thead
                  %tr
                    %th=t('views.user_groups.form.name')
                    %th
                %tbody
                  -@user_groups.each do |user_group|
                    %tr
                      %td=user_group.name
                      %td
                        .pull-right
                          =link_to t('views.general.show'), user_group_url(user_group), class: 'btn btn-purple btn-small'
                          =link_to t('views.general.edit'), edit_user_group_url(user_group), class: 'btn btn-cyan btn-small'
                          -if user_group.destroyable?
                            =link_to t('views.general.delete'), user_group, method: :delete, data: { confirm: t('views.general.delete_confirmation') }, class: 'btn btn-red btn-small'

app/views/user_groups/new.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.user_groups.new.h1')
      =render partial: 'form'

app/views/user_groups/show.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =t('views.user_groups.show.h1')
            \#
            =@user_group.id
      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          .table-box
            .table-responsive
              %table.table.table-bordered.l-margin-top
                %tr
                  %td.col-sm-4=t('views.user_groups.form.name')
                  %td.col-sm-8=@user_group.name
                %tr
                  %td.col-sm-4=t('views.user_groups.form.description')
                  %td.col-sm-8=@user_group.description
                %tr
                  %td.col-sm-4=t('views.user_groups.form.student_user')
                  %td.col-sm-8=tick_or_cross(@user_group.student_user)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.blocked_user')
                  %td.col-sm-8=tick_or_cross(@user_group.blocked_user)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.trial_or_sub_required')
                  %td.col-sm-8=tick_or_cross(@user_group.trial_or_sub_required)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.system_requirements_access')
                  %td.col-sm-8=tick_or_cross(@user_group.system_requirements_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.content_management_access')
                  %td.col-sm-8=tick_or_cross(@user_group.content_management_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.stripe_management_access')
                  %td.col-sm-8=tick_or_cross(@user_group.stripe_management_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.user_management_access')
                  %td.col-sm-8=tick_or_cross(@user_group.user_management_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.developer_access')
                  %td.col-sm-8=tick_or_cross(@user_group.developer_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.home_pages_access')
                  %td.col-sm-8=tick_or_cross(@user_group.home_pages_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.form.user_group_management_access')
                  %td.col-sm-8=tick_or_cross(@user_group.user_group_management_access)
                %tr
                  %td.col-sm-4=t('views.user_groups.show.users')
                  %td.col-sm-8
                    -if @user_group.users.count > 0 && @user_group.users.count < 50
                      -@user_group.users.each do |user|
                        =link_to user.full_name, user
                        %br/
                    -else
                      =link_to users_url, title: t('views.general.tooltips.click_to_view') do
                        =@user_group.users.count
                        =t('views.users.index.h1').downcase
              %p
                =link_to sanitize('&larr; ' + t('views.user_groups.index.h1')), user_groups_url
                |
                =link_to t('views.general.edit'), edit_user_group_url(id: @user_group.id), title: t('views.general.edit_tooltip')