config/routes.rb
Rails.application.routes.draw do

  concern :supports_reordering do
    post :reorder, on: :collection
  end

  # Enable /sidekiq for admin users only
  require 'admin_constraint'
  mount Sidekiq::Web => '/sidekiq', constraints: AdminConstraint.new

  get '404' => redirect('404-page')
  get '500' => redirect('500-page')

  namespace :api do
    post 'stripe_v01', to: 'stripe_v01#create'
    post 'stripe_v02', to: 'stripe_v02#create'
  end

  # all standard, user-facing "resources" go inside this scope
  scope '(:locale)', locale: /en/ do # /en\nl\pl/
    get '404' => redirect('404-page')
    get '500' => redirect('500-page')

    # users and authentication
    resources :users do
      resources :visits, only: [:index, :show]
    end

    get 'new_subscription', to: 'subscriptions#new', as: :new_subscription
    get 'users/:user_id/new_subscription', to: 'subscriptions#new'
    post 'create_subscription/:user_id', to: 'subscriptions#create', as: :create_subscription

    #User Account Verification
    get 'user_verification/:email_verification_code', to: 'user_verifications#update',
        as: :user_verification
    get 'account_verified', to: 'user_verifications#account_verified',
        as: :account_verified
    post 'resend_verification_mail/:email_verification_code', to: 'user_verifications#resend_verification_mail', as: :resend_verification_mail

    # User Sessions
    get 'sign_in', to: 'user_sessions#new', as: :sign_in
    resources :user_sessions, only: [:create]
    get 'sign_out', to: 'user_sessions#destroy', as: :sign_out

    # User Accounts
    get 'account', to: 'user_accounts#account_show', as: :account
    post 'change_password', to: 'user_accounts#change_password', as: :change_password
    patch 'update_user_details', to: 'user_accounts#update_user', as: :update_personal_details
    get 'subscription_invoice/:id', to: 'user_accounts#subscription_invoice', as: :subscription_invoices
    get 'account/change_plan', to: 'subscriptions#change_plan', as: :account_change_plan
    put 'un_cancel_subscription/:id', to: 'subscriptions#un_cancel_subscription', as: :un_cancel_subscription

    resources :user_groups
    resources :student_user_management
    resources :subscription_management do
      get '/invoice/:invoice_id', action: :invoice, as: :invoice
      get '/pdf_invoice/:invoice_id', action: :pdf_invoice, as: :pdf_invoice
      get '/invoice/:invoice_id/charge/:id', action: :charge, as: :invoice_charge
      put '/cancel', action: :cancel, as: :cancel
      put '/un_cancel', action: :un_cancel_subscription, as: :un_cancel_subscription
      put '/immediate_cancel', action: :immediate_cancel, as: :immediate_cancel
    end
    get  'student_user_management/:id/convert_to_student', to: 'student_user_management#convert_to_student', as: :convert_to_student
    patch  'student_user_management/:id/update_to_student', to: 'student_user_management#update_to_student', as: :update_to_student
    resources :users do
      get  '/personal', action: :user_personal_details, as: :personal
      get  '/subscription', action: :user_subscription_status, as: :subscription
      get  '/courses', action: :user_courses_status, as: :courses
      get  '/enrollments', action: :user_enrollments_details, as: :enrollments
      get  '/orders', action: :user_purchases_details, as: :orders
      patch  '/update_courses', action: :update_courses, as: :update_courses
    end
    resources :user_passwords, only: [:new, :edit, :create, :update]
    get 'forgot_password', to: 'user_passwords#new', as: :forgot_password
    get 'reset_password/:id', to: 'user_passwords#edit', as: :reset_password
    get 'set_password/:id', to: 'user_passwords#set_password', as: :set_password
    put 'create_password/:id', to: 'user_passwords#create_password', as: :user_create_password
    post 'manager_resend/:id', to: 'user_passwords#manager_resend_email', as: :manager_resend

    # Internal Landing Pages - post sign-up or upgrade or purchase
    get 'personal_sign_up_complete/:account_activation_code', to: 'student_sign_ups#show', as: :personal_sign_up_complete
    get 'personal_upgrade_complete', to: 'subscriptions#personal_upgrade_complete', as: :personal_upgrade_complete

    get 'courses/:subject_course_name_url/:course_module_name_url(/:course_module_element_name_url)', to: 'courses#show', as: :course
    get 'courses/:subject_course_name_url',
        to: redirect('/%{locale}/library/%{subject_course_name_url}')

    resources :countries, concerns: :supports_reordering
    resources :coupons
    post '/coupon_validation', to: 'coupons#validate_coupon', as: :coupon_validation
    resources :courses, only: [:create] do
      match :create_video_user_log, on: :collection, via: [:post]
      match :video_watched_data, on: :collection, via: [:put, :patch]
    end
    get '/enrollments/basic_create/:subject_course_name_url', to: 'enrollments#basic_create', as: :enrollment_basic_create
    get '/enrollments/admin_show/:id', to: 'enrollments#admin_show', as: :enrollment_admin_show
    get '/enrollments/admin_edit/:id', to: 'enrollments#admin_edit', as: :enrollment_admin_edit
    patch '/enrollments/admin_update/:id', to: 'enrollments#admin_update', as: :enrollment_admin_update
    get '/enrollments/reset_progress/:id', to: 'enrollments#admin_create_new_scul', as: :admin_create_new_scul
    resources :enrollments, only: [:edit, :update, :create]
    get 'course_modules/:subject_course_name_url',
        to: 'course_modules#new',
        as: :new_course_modules_for_subject_course_and_name
    get 'course_modules/:subject_course_name_url', to: 'course_modules#show',
        as: :course_modules_for_subject_course
    resources :course_modules, concerns: :supports_reordering
    resources :course_module_elements, except: [:index], concerns: :supports_reordering
    get 'course_module_elements/:id/quiz_questions_order', to: 'course_module_elements#quiz_questions_order', as: :quiz_questions_order
    resources :currencies, concerns: :supports_reordering

    get '/dashboard', to: 'dashboard#show', as: :student_dashboard

    resources :exam_bodies
    resources :exam_sittings
    resources :groups, concerns: :supports_reordering

    #Sign Up Actions
    get '/student_new', to: 'student_sign_ups#new', as: :new_student
    post '/student_create', to: 'student_sign_ups#create', as: :create_student

    resources :invoices, only: [:index, :show]

    post '/subscribe', to: 'library#subscribe'
    post '/home_page_subscribe', to: 'student_sign_ups#subscribe'
    post '/info_subscribe', to: 'footer_pages#info_subscribe'
    post '/complaints_intercom', to: 'footer_pages#complaints_intercom'
    post '/contact_us_intercom', to: 'footer_pages#contact_us_intercom'
    post '/tutor_contact_form', to: 'library#tutor_contact_form'

    # Library Structure

    get 'library', to: 'library#index', as: :library
    get 'library/:group_name_url', to: 'library#group_show', as: :library_group
    get 'library/:group_name_url/:subject_course_name_url', to: 'library#course_show', as: :library_course

    resources :management_consoles
    get '/system_requirements', to: 'management_consoles#system_requirements', as: :system_requirements
    resources :mock_exams, concerns: :supports_reordering
    resources :orders, except: [:new]
    get 'order/new/:product_id', to: 'orders#new', as: :new_order
    get 'order/order_complete/:reference_guid', to: 'orders#order_complete', as: :order_complete
    resources :products
    resources :quiz_questions, except: [:index], concerns: :supports_reordering

    get '/reports', to: 'reports#index', as: :reports
    get '/export_users', to: 'reports#export_users', as: :export_users
    get '/export_users_monthly', to: 'reports#export_users_monthly', as: :export_users_monthly
    get '/export_users_with_enrollments', to: 'reports#export_users_with_enrollments', as: :export_users_with_enrollments
    get '/export_visits', to: 'reports#export_visits', as: :export_visits
    get '/export_courses', to: 'reports#export_courses', as: :export_courses
    get '/export_enrollments', to: 'reports#export_enrollments', as: :export_enrollments


    resources :subject_courses, concerns: :supports_reordering do
      get 'edit_tutors', action: :edit_tutors, as: :edit_course_tutors
      patch 'update_tutors', action: :update_tutors, as: :update_course_tutors
    end
    get 'subject_courses/:id/course_modules_order', to: 'subject_courses#course_modules_order', as: :course_modules_order
    post 'subject_courses/:id/update_user_logs', to: 'subject_courses#update_student_exam_tracks', as: :subject_course_update_user_logs
    get 'subject_courses/:id/resources', to: 'subject_courses#subject_course_resources', as: :course_resources
    get 'subject_courses/:id/new_subject_course_resources', to: 'subject_courses#new_subject_course_resources', as: :new_course_resources
    post 'subject_courses/:id/create_subject_course_resources', to: 'subject_courses#create_subject_course_resources', as: :create_course_resources

    resources :subscriptions, only: [:update, :destroy]
    resources :subscription_payment_cards, only: [:create, :update, :destroy]
    resources :subscription_plans
    resources :subscription_plan_categories
    get '/all_subscriptions', to: 'subscription_plans#all_subscriptions', as: :all_subscriptions
    get '/subscription_show/:id', to: 'subscription_plans#subscription_show', as: :subscription_show

    resources :subject_course_resources
    get 'pricing', to: 'subscription_plans#public_index', as: :pricing
    get 'acca_info', to: 'footer_pages#acca_info'
    get 'contact', to: 'footer_pages#contact'
    get 'privacy_policy', to: 'footer_pages#privacy_policy'
    get 'terms_and_conditions', to: 'footer_pages#terms_and_conditions'
    get 'profile/:id', to: 'footer_pages#profile', as: :profile
    get 'profiles', to: 'footer_pages#profile_index', as: :tutors

    resources :user_notifications

app/views/user_management/_form.html.haml
=form_for(@user, url: user_management_url(@user), html: {class: 'form-horizontal', role: 'form', multipart: true}) do |f|
  =render partial: '/layouts/error_messages', locals: {thing: @user, message: nil}
  .row
    .col-md-12.l-margin-bottom-big
      .col-md-6
        =f.label :email, t('views.users.form.email'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_field :email, placeholder: t('views.users.form.email_placeholder'), class: 'form-control', style: 'border-radius: 6px;'
        %br/
        =f.label :user_group_id, t('views.users.form.user_group_id'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.collection_select :user_group_id, @user_groups, :id, :name, {include_blank: t('views.general.select')}, {class: 'form-control', style: 'border-radius: 6px;'}
        %br/
        =f.label :country_id, t('views.users.form.country_id'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.collection_select :country_id, @countries, :id, :name, {include_blank: t('views.general.select')}, {class: 'form-control', style: 'border-radius: 6px;'}
        %br/
        =f.label :date_of_birth, t('views.users.form.date_of_birth'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_field :date_of_birth, placeholder: t('views.users.form.date_of_birth_placeholder'), class: 'form-control', style: 'border-radius: 6px;', data: {'date-format' => t('controllers.application.datepicker_datetime_format')}, id: 'datetimepicker'



      .col-md-6
        =f.label :first_name, t('views.users.form.first_name'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_field :first_name, placeholder: t('views.users.form.first_name_placeholder'), class: 'form-control', style: 'border-radius: 6px;'
        %br/
        =f.label :last_name, t('views.users.form.last_name'), class: 'control-label'
        .input-group.input-group-lg.full-width
          =f.text_field :last_name, placeholder: t('views.users.form.last_name_placeholder'), class: 'form-control', style: 'border-radius: 6px;'
        %br/
        %br/
        %label
          =t('views.users.form.active')
          =f.check_box :active

        %br/
        %br/
        %br/
        =f.label :profile_image, t('views.users.form.profile_image'), class: 'control-label'
        -if f.object.profile_image.url
          =image_tag f.object.profile_image.url, class: 'img-responsive'
          %br/
          Upload a replacement if you wish
          %br/
        =f.file_field :profile_image, class: 'form-control'


  .row
    .col-md-12
      =f.label :description, t('views.users.form.description'), class: 'control-label'
      .input-group.input-group-lg.full-width
        =f.text_area :description, as: :summernote, placeholder: t('views.users.form.description_placeholder'), class: 'form-control', style: 'border-radius: 6px;', id: 'editor'


  .row
    =f.submit t('views.general.save'), class: 'btn btn-red'
    =link_to t('views.general.cancel'), user_management_index_url, class: 'btn btn-cyan'


:javascript
  $(function () {
    $('#datetimepicker').datetimepicker();
      format: 'DD/MM/YYYY'
  });
  $('#editor').summernote({
    disableDragAndDrop: true,
    height: 150
  });

app/views/user_management/_tabs.html.haml
.admin-nav
  %ul.admin-nav-block
    %li
      =link_to 'Users', user_management_index_url
    %li
      =link_to 'User Groups', user_groups_url
    %li
      =link_to 'User Visits', visits_all_index_url

app/views/user_management/import_csv_upload.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-8.col-sm-offset-2.text-center
          %h1.l-margin-bottom.l-margin-top.text-center.h-separator.h-separator-center
            =t('models.users.import_csv')
          %h6
            =t('models.users.sidekiq_explanation')
          %h6.l-margin-top{style: 'color: #EF5153;'}
            =t('models.users.dont_reload')

      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          .col-sm-6
            .table-box
              .table-responsive
                %table.table
                  %thead
                    %tr
                      %th='New Users - Invite Email'
                      %th
                  %tbody
                    -@new_users.each do |user_email|
                      %tr
                        %td=user_email
                        %td='Processing'


          .col-sm-6
            .table-box
              .table-responsive
                %table.table
                  %thead
                    %tr
                      %th='Expired Trial Users - Trial Expired Email'
                      %th
                  %tbody
                    -@existing_users.each do |user|
                      %tr
                        %td=user.email
                        %td=user.id


      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          =link_to 'Return', user_management_index_url, class: 'btn btn-cyan'
          =link_to 'Sidekiq', sidekiq_web_path, target: '_blank', class: 'btn btn-red'

app/views/user_management/index.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            Users

      .row.l-margin-top.l-margin-bottom
        .col-md-12
          =render partial: 'management_consoles/user_management_nav'

      .row.l-margin-top.l-margin-bottom
        .col-sm-6.l-margin-top
          %a{data: {remodal: {target: 'csv-upload-modal'}}, class: 'btn btn-purple'}
            Bulk Invite Users
          =link_to t('views.general.add_user'), new_user_management_url, class: 'btn btn-red l-padding-side-3x text-bold', title: t('views.general.new_tooltip')


        .col-sm-4.col-sm-offset-2.l-margin-top
          =form_tag(user_management_index_url, method: :get, role: 'form', class: 'form-inline input-group-lg') do
            .form-group.input-group.input-group-lg
              =text_field_tag :search_term, params[:search_term], class: 'form-control', placeholder: t('views.general.search'), onblur: 'this.form.submit(); return false;'
              .input-group-addon{style: 'background-color: #EE5457; color: #fff;'}
                %span.glyphicon.glyphicon-search

        .col-md-12.l-margin-top-big
          .corporate-box-item.table-box
            .table-responsive
              %table.table{style: 'font-size: 18px;'}
                %thead
                  %tr
                    %th=t('views.users.form.full_name')
                    %th=t('views.users.form.email')
                    %th=t('views.users.form.email_verified')
                    %th=t('views.users.form.user_group_id')
                    %th=t('views.users.form.subscription_status')
                    %th
                    %th
                %tbody
                  -@users.each do |user|
                    %tr
                      %td=user.full_name
                      %td=user.email
                      %td
                        =tick_or_cross(user.email_verified)
                      %td=user.user_group.try(:name)
                      %td=user.user_account_status
                      %td
                        =link_to t('views.general.view'), user_management_url(user), class: 'btn btn-purple btn-small'
                      %td
                        =link_to t('views.general.edit'), edit_user_management_url(user), class: 'btn btn-cyan btn-small'

              .col-sm-10.user-pagination
                =will_paginate @users, renderer: BootstrapPagination::Rails

=render partial: 'csv_import_modal'

app/views/user_management/preview_csv_upload.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.l-margin-top.text-center.h-separator.h-separator-center
            =t('views.dashboard.admin.preview_csv.h1')
          %p
            Please check that the data below is correct and then click Submit
      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          =form_tag(import_csv_upload_path, authenticity_token: true, id: 'import_csv_corporate_students_form', role: 'form', class: 'form-horizontal') do
            .corporate-box-item.table-box
              .table-responsive
                %table.table{style: 'font-size: 18px;'}
                  %thead
                    %tr
                      %th
                        Email
                      %th
                        First Name
                      %th
                        Last Name
                      %th
                        Errors
                  %tbody
                    -@csv_data.each_with_index do |csd, idx|
                      %tr{id: "csvdata-#{idx}"}
                        =hidden_field_tag "csvdata[#{idx}][email]", csd[:values][0]
                        =hidden_field_tag "csvdata[#{idx}][first_name]", csd[:values][1]
                        =hidden_field_tag "csvdata[#{idx}][last_name]", csd[:values][2]
                        %td
                          =csd[:values][0]
                        %td
                          =csd[:values][1]
                        %td
                          =csd[:values][2]
                        %td=csd[:error_messages].map {|em| "<p>#{em}</p>"}.join("\n").html_safe

              .row
                .col-sm-12
                  -unless @has_errors
                    =submit_tag 'Submit', class: 'btn btn-red'
                  =link_to t('views.general.cancel'), user_management_index_url, class: 'btn btn-cyan'

app/views/user_management/show.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =@user.full_name
      .row.l-margin-top.l-margin-bottom
        .col-md-12
          =render partial: 'user_tabs'

      .row.l-margin-top-huge.l-margin-bottom-huge
        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                =@user_sessions_count
              .h6
                Sessions

        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                =@enrollments.count
              .h6
                Enrollments

        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                =humanize_datetime(@user.trial_start_date)
              .h6
                Signed Up

        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                -if @user.last_login_at
                  =humanize_datetime(@user.last_login_at)
                -else
                  ='-'
              .h6
                Last Active

      .row.l-margin-top.l-margin-bottom-huge
        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                =tick_or_cross(@user.active_subscription)
              .h6
                Active Subscription

        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                =@user.id
              .h6
                User ID

        .col-md-3.col-sm-3.col-xs-6
          .stats-box
            .stats-box-inner
              .h3
                -if @user.enrollments.any?
                  =@user.enrollments.first.student_number
                -else
                  ='-'
              .h6
                Student Number


      .row.l-margin-top.l-margin-bottom-huge
        -if !@user.email_verified && @user.email_verification_code
          .col-md-3.col-sm-3.col-xs-6
            =link_to 'Resend Verification Email', admin_resend_verification_mail_url(@user.email_verification_code), class: 'btn btn-purple '

        -if @user.destroyable?
          .col-md-3.col-sm-3.col-xs-6
            =link_to 'Delete User', user_management_url(@user), method: :delete, data: { confirm: t('views.general.delete_confirmation') }, class: 'btn btn-red'

        -if @user.visits.any?
          .col-md-3.col-sm-3.col-xs-6
            =link_to 'User Visits', user_visits_url(@user), class: 'btn btn-cyan'

        .col-md-3.col-sm-3.col-xs-6
        .col-md-3.col-sm-3.col-xs-6

app/views/user_management/user_personal_details.html.haml
.l-section-small.is-bg-asphalt
  .l-wrap
    .container-fluid
      .row.l-margin-bottom
        .col-md-12.text-center
          %h1.l-margin-bottom.text-center.h-separator.h-separator-center{style: 'letter-spacing:1.5px;'}
            =@user.full_name
      .row.l-margin-top.l-margin-bottom
        .col-md-12
          =render partial: 'user_tabs'


      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          .box-item
            .col-sm-10.l-margin-top
              .col-sm-6
                .h3
                  Email
                .h6
                  =@user.email

              .col-sm-6
                .h3
                  ="D.O.B"
                .h6
                  =@user.date_of_birth || '--------'

            .col-sm-2.l-margin-top
              =link_to 'Edit Details', edit_user_management_url(@user), class: 'btn btn-red'


            .col-sm-10.l-margin-top-big
              .col-sm-6
                .h3
                  First Name
                .h6
                  =@user.first_name

              .col-sm-6
                .h3
                  Last Name
                .h6
                  =@user.last_name


      .row.l-margin-top.l-margin-bottom
        .col-md-12.l-margin-top-big
          .box-item
            .col-sm-12.l-margin-top-big
              .col-sm-6
                .h3
                  Country
                .h6
                  -if @user.country
                    =@user.country.name
                  -else
                    ='-------'

              .col-sm-6
                .h3
                  Last IP Address
                .h6
                  =@user.last_login_ip.to_s

            .col-sm-12.l-margin-top-big
              .col-sm-6
                .h3
                  User Group
                .h6
                  =@user.user_group.name

              .col-sm-6
                .h3
                  Stripe Customer ID
                .h6
                  =@user.stripe_customer_id


            .col-sm-12.l-margin-top-big
              .col-sm-6
                .h3
                  Account Created
                .h6
                  =humanize_datetime(@user.created_at)

              .col-sm-6
                .h3
                  Trial Started
                .h6
                  =humanize_datetime(@user.trial_start_date)



            .col-sm-12.l-margin-top-big
              .col-sm-6
                .h3
                  Account Type
                .h6
                  =@user.user_account_status
              .col-sm-6